import 'package:flutter/material.dart'
    show
        Color,
        Colors,
        Curves,
        EdgeInsets,
        FontWeight,
        LinearGradient,
        MainAxisAlignment,
        TextAlign,
        TextStyle;
import 'package:flutter/widgets.dart' show CrossAxisAlignment;
import 'package:flutter/physics.dart' show SpringDescription;
import 'package:flutter_lyric/core/lyric_scroll_behavior.dart';
import 'package:flutter_lyric/core/lyric_style.dart';

abstract class LyricStyles {
  /// Apple Music inspired large, left-aligned, depth-aware lyric treatment.
  static final appleMusic = LyricStyle(
    textStyle: const TextStyle(
      fontFamily: 'CupertinoSystemDisplay',
      fontSize: 25,
      height: 1.14,
      letterSpacing: 0,
      color: Color(0x73FFFFFF),
      fontWeight: FontWeight.w700,
    ),
    activeStyle: const TextStyle(
      fontFamily: 'CupertinoSystemDisplay',
      fontSize: 30,
      height: 1.12,
      letterSpacing: 0,
      color: Color(0x8FFFFFFF),
      fontWeight: FontWeight.w800,
    ),
    translationStyle: const TextStyle(
      fontFamily: 'CupertinoSystemText',
      fontSize: 15,
      height: 1.25,
      letterSpacing: 0,
      color: Color(0x66FFFFFF),
      fontWeight: FontWeight.w600,
    ),
    translationActiveColor: const Color(0xD9FFFFFF),
    lineTextAlign: TextAlign.left,
    contentAlignment: CrossAxisAlignment.start,
    contentPadding: const EdgeInsets.fromLTRB(24, 32, 24, 72),
    lineGap: 24,
    translationLineGap: 6,
    selectionAnchorPosition: 0.42,
    activeAnchorPosition: 0.36,
    selectionAlignment: MainAxisAlignment.start,
    activeAlignment: MainAxisAlignment.start,
    fadeRange: FadeRange(top: 0.12, bottom: 0.26),
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: const Duration(milliseconds: 420),
    scrollBehavior: SpringScrollConfig(
      springDescription: SpringDescription.withDampingRatio(
        mass: 1,
        stiffness: 180,
        ratio: 0.86,
      ),
    ),
    enableSwitchAnimation: true,
    switchEnterDuration: const Duration(milliseconds: 440),
    switchExitDuration: const Duration(milliseconds: 360),
    switchEnterCurve: Curves.easeOutBack,
    switchExitCurve: Curves.easeOutCubic,
    selectionAutoResumeMode: SelectionAutoResumeMode.neverResume,
    selectionAutoResumeDuration: const Duration(milliseconds: 320),
    activeAutoResumeDuration: const Duration(milliseconds: 2600),
    activeHighlightGradient: const LinearGradient(
      colors: [Color(0xFFF7F7FA), Colors.white],
    ),
    activeHighlightExtraFadeWidth: 18,
    inactiveLineBlurRadius: 1.6,
    activeLineGlowRadius: 5.5,
    activeLineGlowOpacity: 0.34,
    highlightTransitionDuration: const Duration(milliseconds: 90),
  );

  static final default1 = LyricStyle(
    textStyle: const TextStyle(fontSize: 14, color: Colors.white70),
    activeStyle: const TextStyle(fontSize: 16, color: Colors.white),
    translationStyle: const TextStyle(fontSize: 12, color: Colors.white70),
    lineTextAlign: TextAlign.center,
    lineGap: 26,
    translationLineGap: 10,
    contentAlignment: CrossAxisAlignment.center,
    contentPadding:
        const EdgeInsets.only(top: 500, left: 20, right: 20, bottom: 20),
    selectionAnchorPosition: 0.48,
    fadeRange: FadeRange(top: 80, bottom: 80),
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: const Duration(milliseconds: 240),
    scrollDurations: {
      500: const Duration(milliseconds: 500),
      1000: const Duration(milliseconds: 1000),
    },
    enableSwitchAnimation: false,
    selectionAutoResumeMode: SelectionAutoResumeMode.selecting,
    selectionAutoResumeDuration: const Duration(milliseconds: 320),
    activeAutoResumeDuration: const Duration(milliseconds: 3000),
    activeHighlightColor: Colors.yellow,
    switchEnterDuration: const Duration(milliseconds: 300),
    switchExitDuration: const Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeOutBack,
    switchExitCurve: Curves.easeOutQuint,
    selectionAlignment: MainAxisAlignment.center,
  );

  static final default2 = LyricStyle(
    textStyle:
        const TextStyle(fontSize: 12, color: Colors.white70, height: 1.2),
    activeStyle: const TextStyle(
      fontSize: 18,
      height: 1.2,
      color: Colors.white,
      fontWeight: FontWeight.w600,
    ),
    translationStyle: const TextStyle(fontSize: 12, color: Colors.white70),
    translationActiveColor: Colors.white,
    lineTextAlign: TextAlign.left,
    lineGap: 20,
    translationLineGap: 5,
    contentAlignment: CrossAxisAlignment.start,
    contentPadding:
        const EdgeInsets.only(top: 40, left: 20, right: 20, bottom: 20),
    selectionAnchorPosition: 0.5,
    activeAnchorPosition: 100,
    fadeRange: FadeRange(top: 40, bottom: 80),
    selectionAlignment: MainAxisAlignment.end,
    activeAlignment: MainAxisAlignment.start,
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: const Duration(milliseconds: 240),
    scrollDurations: {
      500: const Duration(milliseconds: 500),
      1000: const Duration(milliseconds: 1000),
    },
    enableSwitchAnimation: true,
    selectionAutoResumeMode: SelectionAutoResumeMode.neverResume,
    selectionAutoResumeDuration: const Duration(milliseconds: 320),
    activeAutoResumeDuration: const Duration(milliseconds: 2000),
    switchEnterDuration: const Duration(milliseconds: 500),
    switchExitDuration: const Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeIn,
    switchExitCurve: Curves.easeOut,
    activeHighlightGradient: const LinearGradient(
      colors: [Color(0xFF3bb2b8), Color(0xFF42e695)],
    ),
    activeHighlightExtraFadeWidth: 40,
  );
  static final single = LyricStyle(
    textStyle:
        const TextStyle(fontSize: 14, color: Colors.white70, height: 1.2),
    activeStyle: const TextStyle(
      fontSize: 24,
      height: 1.2,
      color: Colors.white,
      fontWeight: FontWeight.w600,
    ),
    translationStyle: const TextStyle(fontSize: 12, color: Colors.white70),
    translationActiveColor: Colors.white,
    lineTextAlign: TextAlign.center,
    lineGap: 0,
    translationLineGap: 10,
    activeLineOnly: true,
    disableTouchEvent: true,
    contentAlignment: CrossAxisAlignment.center,
    selectionAnchorPosition: 0.5,
    contentPadding: const EdgeInsets.only(top: 800, left: 20, right: 20),
    fadeRange: FadeRange(top: 0, bottom: 0),
    selectionAlignment: MainAxisAlignment.center,
    activeAlignment: MainAxisAlignment.center,
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: const Duration(milliseconds: 0),
    enableSwitchAnimation: false,
    selectionAutoResumeMode: SelectionAutoResumeMode.neverResume,
    selectionAutoResumeDuration: const Duration(milliseconds: 320),
    activeAutoResumeDuration: const Duration(milliseconds: 3000),
    activeHighlightColor: const Color.fromARGB(255, 120, 255, 124),
    switchEnterDuration: const Duration(milliseconds: 500),
    switchExitDuration: const Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeIn,
    switchExitCurve: Curves.easeOut,
    activeHighlightExtraFadeWidth: 40,
  );
}
