// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kikoenai_core/core/model/album/circle.dart';
import 'package:kikoenai_core/core/model/album/other_language_edition.dart';
import 'package:kikoenai_core/core/model/album/rank.dart';
import 'package:kikoenai_core/core/model/album/rate_count_detail.dart';
import 'package:kikoenai_core/core/model/album/tag.dart';
import 'package:kikoenai_core/core/model/album/va.dart';
import 'package:kikoenai_core/core/model/album/work.dart';
import 'package:kikoenai_core/core/model/album/work_info.dart';
import 'package:kikoenai_core/core/model/history/history_entry.dart';
import 'package:kikoenai_core/core/model/local_media/file_node.dart';
import 'package:kikoenai_core/core/model/local_media/file_scanner_state.dart';
import 'package:kikoenai_core/core/model/local_media/scan_mode.dart';
import 'package:kikoenai_core/core/model/lyrics/lyric_model.dart';
import 'package:kikoenai_core/core/model/player/playback_session.dart';
import 'package:kikoenai_core/core/model/player/player_state.dart';
import 'package:kikoenai_core/core/model/player/progress_state.dart';
import 'package:kikoenai_core/core/model/shared/search_tag.dart';
import 'package:kikoenai_core/core/model/user/auth_response.dart';
import 'package:kikoenai_core/core/model/user/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppPlayerStateAdapter());
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CircleAdapter());
    registerAdapter(FileNodeAdapter());
    registerAdapter(HistoryEntryAdapter());
    registerAdapter(LyricConfigModelAdapter());
    registerAdapter(NodeSourceAdapter());
    registerAdapter(NodeStatusAdapter());
    registerAdapter(NodeTypeAdapter());
    registerAdapter(OtherLanguageEditionAdapter());
    registerAdapter(PlaybackItemAdapter());
    registerAdapter(PlaybackSessionAdapter());
    registerAdapter(ProgressBarStateAdapter());
    registerAdapter(RankAdapter());
    registerAdapter(RateCountDetailAdapter());
    registerAdapter(ScanModeAdapter());
    registerAdapter(ScanTargetAdapter());
    registerAdapter(SearchTagAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(VAAdapter());
    registerAdapter(WorkAdapter());
    registerAdapter(WorkInfoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppPlayerStateAdapter());
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CircleAdapter());
    registerAdapter(FileNodeAdapter());
    registerAdapter(HistoryEntryAdapter());
    registerAdapter(LyricConfigModelAdapter());
    registerAdapter(NodeSourceAdapter());
    registerAdapter(NodeStatusAdapter());
    registerAdapter(NodeTypeAdapter());
    registerAdapter(OtherLanguageEditionAdapter());
    registerAdapter(PlaybackItemAdapter());
    registerAdapter(PlaybackSessionAdapter());
    registerAdapter(ProgressBarStateAdapter());
    registerAdapter(RankAdapter());
    registerAdapter(RateCountDetailAdapter());
    registerAdapter(ScanModeAdapter());
    registerAdapter(ScanTargetAdapter());
    registerAdapter(SearchTagAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(VAAdapter());
    registerAdapter(WorkAdapter());
    registerAdapter(WorkInfoAdapter());
  }
}
